# Generated by Django 6.0.4 on 2026-04-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active')], db_index=True, default='draft', max_length=10),
        ),
    ]
