# Generated by Django 6.0.4 on 2026-04-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcategory_options_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='alt_text',
        ),
    ]
