# Generated by Django 6.0.4 on 2026-04-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_duration_video_views_count_videounlock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='income',
        ),
    ]
