# Generated by Django 6.0.4 on 2026-04-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
