# Generated by Django 6.0.4 on 2026-04-26 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_videoorder_delete_videounlock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='videoorder',
            old_name='unlocked_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='videoorder',
            name='payment_reference',
        ),
        migrations.AddField(
            model_name='videoorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='videoorder',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
