# Generated by Django 6.0.4 on 2026-04-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_alter_videoorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='trailer',
            field=models.FileField(default=1, upload_to='video_trailers/'),
            preserve_default=False,
        ),
    ]
