# Generated by Django 6.0.4 on 2026-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0011_videoorder_paypal_approval_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
