# Generated by Django 6.0.4 on 2026-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0012_videoorder_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cf_stream_uid',
            field=models.CharField(blank=True, help_text='Cloudflare Stream UID', max_length=100, null=True),
        ),
    ]
