# Generated by Django 6.0.4 on 2026-04-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_cart_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
